### PR TITLE
Add GitHub Actions Build+Test

### PR DESCRIPTION
**Pull request by md-5**
Checks that lombok still builds and functions across a wide range of JVMs.
Also fixes a failiure of the Java 12 tests.

### CODE REVIEW

**Comment by Rawi01** [comment]
I did something similar [here](https://github.com/Rawi01/lombok/tree/ci) and added a [post in the google group](https://groups.google.com/g/project-lombok/c/vhdEExQnpiw) some time ago but still wait for feedback.

**Comment by Rawi01** [comment]
I rebased my version and slightly modified it to pass again, the main differences is that your version runs `test.javacCurrent`, `test.eclipse-202006`, `test.javac6` and `test.javac8` on JDK 11-16 and my version only runs a single goal . I think thats the better approach because the name of the failed job matches the failing test, WDYT? 
If that would be okay for you I would add my commits to this PR so everything can be merged together.

**Comment by md-5** [comment]
@Rawi01 the javac6 and java8 tests are special in that they use class files from those versions but on the **current VM**, which is why I included them in all jobs to test eg java 15 vm + java 8 class files

**Comment by Rawi01** [comment]
That's right but in a real world scenario no one will compile code like this 😂

**Comment by Rawi01** [comment]
I have also added some integration tests using the provided docker images

**Comment by rspilker** [comment]
Oh, and using all those docker images looks great @Rawi01!

**Comment by Rawi01** [comment]
@rspilker I think it does not block anything unless you enable it (https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests). If you want to simply try it out you can also fork the repo as I did.

**Comment by Rawi01** [comment]
@rspilker I just noticed that you added some code quality actions, do you think that we can also manage to merge this/some of my changes/both?

**Comment by bxb100** [comment]
> Hi,
> 
> I'm trying to figure out how this works. Is there a way to test this, without blocking commits or pull requests?

@rspilker 
IMHO, you can fork this repo and checkout this PR, then add `workflow_dispatch`[^1] event trigger to manually run

[^1]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

**Comment by md-5** [comment]
This was added

**Pull request closed without merging**
