### PR TITLE
Copy JsonProperty annotation to getter

### PR DESCRIPTION
**Pull request by XenoAmess**
I strongly suggest copy JsonProperty annotation onto getter functions.
tests applied.

### CODE REVIEW

**Comment by janrieke** [comment]
I don't understand why copying is necessary at all. IIRC Jackson considers field, getter, and setter as a unit; an annotation on one of them holds for all.

**Comment by XenoAmess** [comment]
> I don't understand why copying is necessary at all. IIRC Jackson considers field, getter, and setter as a unit; an annotation on one of them holds for all.
> Shouldn't Lombok simply stop copying those annotations at all (except for builders)?

I provided the test classes. You can just run it to see.

**Comment by XenoAmess** [comment]
Hi. is there any news?

**Comment by janrieke** [comment]
Jackson's behavior appears strange to me. Why should _property annotation merging_ not occur when there is no setter?
I did not find a hint in the documentation that explains this. Thus, I consider this a Jackson bug. Could you file an issue at [Jackson](https://github.com/FasterXML/jackson-databind)?

**Comment by XenoAmess** [comment]
> Jackson's behavior appears strange to me. Why should _property annotation merging_ not occur when there is no setter? I did not find a hint in the documentation that explains this. Thus, I consider this a Jackson bug. Could you file an issue at [Jackson](https://github.com/FasterXML/jackson-databind)?

issue created https://github.com/FasterXML/jackson-core/issues/735

**Comment by janrieke** [comment]
So my conclusion is that this is (again) a result of the crappy bean-spec. Question is: Should lombok once again try fixing this by copying the annotation?

When lombok introduced/extended the copy-to-setter mechanism, that already had unintended side-effects: #2778, #2769
Right now, once lombok copies an annotation, there is no way for users to stop lombok from doing so. So users would have to remove the lombok annotation and implement the generated methods by themselves. That's a workaround I personally do not like.
In contrast, the workaround for this case is quite easy: `@Getter(onMethod_=@JsonProperty("xYz"))`

However, you may argue that if lombok copies an annotation to a setter, then it should also be put on a getter. I agree with that. Right now, I don't see a reason why this would cause further issues with Jackson, but I did not investigate further. However, I still vote for lombok to stop copying completely (except for builders). But that's a decision for the maintainers.

If the maintainers decide that lombok should also copy Jackson annotations to the getter, this PR is most likely not sufficient. There are several other Jackson annotations that we have to look at, and we need the make sure that this really does not break any more use-cases.

**Comment by XenoAmess** [comment]
> However, you may argue that if lombok copies an annotation to a setter, then it should also be put on a getter. I agree with that. 

Yes, I really do.

I really hate inconsistency like this... 

I can't give very much detail as that is somehow company secret, but it has really already bring me some trouble.

**Comment by rzwitserloot** [comment]
If @janrieke is not willing to call that the right move is unambiguously to copy it to the getter, well, my (and @rspilker's) thorough lack of experience with jackson means we can't call it either. No go.

**Pull request closed without merging**
