### PR TITLE
Add support for JDK17

### LINKED ISSUE #2898: [FEATURE] JDK 17 support
Hello lombok team,

JDK 17 release is just around the corner and it would be very convenient to have at least a lombok snapshot to start working on the migration.

Thanks !

### PR DESCRIPTION
**Pull request by Rawi01**
This PR fixes #2898

### CODE REVIEW

**Comment by rzwitserloot** [comment]
Heh. Back in the lombok saddle today and I thought to myself: Rats! I wanted to check JDK17 before its official release date. But, you beat me to the punch. Nice!

**Comment by timtebeek** [comment]
Will this also resolve [the "Cannot read field "bindingsWhenTrue" because "currentBindings" is null" issue](https://stackoverflow.com/questions/69184925/gradle-7-2-java-17-build-issue-java-lang-nullpointerexception-cannot-read-field) when using `@Singular`?

**Comment by rzwitserloot** [comment]
@timtebeek I think so. I just released a new edge with this patch applied; give it a test :)

https://projectlombok.org/download-edge

**Comment by timtebeek** [comment]
Confirmed fixed by @chrisgleissner in https://github.com/projectlombok/lombok/issues/2963#issuecomment-920540663 ; Thanks for the (late night) work!

**Pull request merged**
