### PR TITLE
Rename log to Log to comply with link in java docs

### PR DESCRIPTION
**Pull request by mucharafal**
Currently, links in Java docs have the path `feature/Log`, which such path doesn't exist on the website (there is `feature/log` instead)

### CODE REVIEW

**Comment by edysli** [comment]
Fixes #3267

**Comment by rzwitserloot** [comment]
Actually, it's the javadoc that is wrong. The reason we call the log feature page 'log' and not 'Log' is because 'Log' suggests that it is the docs for a hypothetical `@Log`. It's not; it's the docs for all the various log-related lombok annos.

Thanks for noticing and pointing the way to how to fix it :). I've updated the javadoc in just-pushed commit 731bb185077918af8bc1e6a9e6bb538b2d3fbbd8.

To cover for existing (wrong) URLs out in the wild, we're going to add a redirect from `/features/Log` to `/features/log`.

**Comment by mucharafal** [comment]
Thanks for the feedback and for fixing the issue!

**Comment by juriad** [comment]
aaa

**Pull request closed without merging**
