### PR TITLE
Add support for JDK 19

### PR DESCRIPTION
**Pull request by Rawi01**
This PR requires a new lombok.patcher release (0.46) with ASM 9.3.

Issues: #3211

### CODE REVIEW

**Comment by SimSonic** [comment]
@Rawi01 hi, it is possible for you to finish PR?

**Comment by Rawi01** [comment]
I left this as a draft because I had no time to test it properly and it needs an updated lombok patcher (that's why the automated build fails).

**Comment by Rawi01** [comment]
@rzwitserloot This PR can be merged as soon as you update the patcher

**Comment by alexanderankin** [comment]
related patcher pr https://github.com/projectlombok/lombok.patcher/pull/11

**Comment by HJK181** [comment]
Any updates?

**Comment by rzwitserloot** [comment]
Lombok release with JDK19 support imminent.

**Comment by savvyben** [comment]
How imminent?

**Comment by rspilker** [comment]
We want to ship a release tomorrow. But we didn't get any feedback, negative nor positive, on the edge release, which does not give us much confidence in the release.

**Comment by Harmelodic** [comment]
Feedback from me:

Using lombok `1.18.24` with JDK 19, I got the error:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
[ERROR] /redacted/path/to/class/Thing.java:[10,1] Ignoring static constructor name: explicit @XxxArgsConstructor annotation present; its `staticName` parameter will be used.
```
where the class was using `@Value(staticConstructor = "of")`


Using lombok `edge-SNAPSHOT` with JDK 19, I got:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

So it's a big 👍 from me!

**Comment by SimSonic** [comment]
A little bit of positive feedback.

Enterprise multi-module maven project with codebase size up to 280k+ LoC recompiles successfully, all tests are green.

Using lombok-edge.jar downloaded from site and both JDK 17 and 19.

**Comment by dstango** [comment]
Question:
In https://github.com/projectlombok/lombok/issues/3180#issuecomment-1107460862 and https://github.com/projectlombok/lombok/issues/3180#issuecomment-1139721411 you said you intended to (maybe partly) roll-back the copying of constraint annotations to getters/setters and release a 1.26 soon. 
I can't find any PR in the issue #3180, that resolves the issue (plus it's still open). Do I miss something? Or did you change your mind about it?

**Comment by Rawi01** [comment]
@dstango https://github.com/projectlombok/lombok/commit/1473389f397579a224d57b496f6387f3b8cbb6a9

**Comment by dstango** [comment]
@Rawi01 thank you!

**Comment by savvyben** [comment]
when is the release being cut?

**Pull request merged**
